#!/bin/bash
# This is a simple script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the build step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

data="${OPENSHIFT_DATA_DIR}/assets"
assets="${OPENSHIFT_REPO_DIR}/public"

# Make the data directory if it doesn't exist
if [ ! -d "$data" ]; then
mkdir $data;
fi

# Remove the assets directory if it's empty
find $assets/assets -maxdepth 0 -type d -empty -delete 2> /dev/null

# Try to make the symlink
ln -s $data $assets 2> /dev/null
if [ $? -gt 0 ]; then
echo "Unable to create symlink to assets directory, using existing directory in repository"
fi